# Generated by Django 4.1 on 2022-09-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarangWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_movie', models.CharField(max_length=255)),
                ('movie_title', models.CharField(max_length=255)),
                ('movie_rate', models.IntegerField()),
                ('release_date', models.DateField()),
                ('movie_review', models.CharField(max_length=255)),
            ],
        ),
    ]
