# Generated by Django 4.1 on 2022-09-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_rename_barangwishlist_mywatchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='mywatchlistitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_movie', models.TextField()),
                ('movie_title', models.TextField()),
                ('movie_rate', models.IntegerField()),
                ('release_date', models.DateField()),
                ('movie_review', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='MyWatchList',
        ),
    ]
